import { sessionSorts, sessionTimeFilter } from "./utils.js";
export const state = {
    currentSort: sessionSorts.Recency.ascending,
    currentFilter: sessionTimeFilter.Day,
    timerStarted: false,
    timerPaused: true,
    isSessionListHidden: true,
    sessionSaved: true,
    localCopyCreated: false,
    stopwatchMode: true,
};
export const globals = {
    countdownDurationSec: 3600,
    sessionDurationSec: 0,
    allSessions: {},
    sessionTags: [],
    allSessionsByDate: {},
    sessionsToPopulate: [],
    sessionTimerId: 0,
    localSessionId: 0,
    pauseStartedDate: 0,
    sessionStartedDate: null,
    pauseEndedDate: null,
    sessionEndedDate: 0,
    sessionInfo: {
        StartedAt: 0,
        EndedAt: 0,
        Duration: "",
        PausesInSession: [],
        Title: "",
        Description: "",
        Tags: [],
        Resources: "",
    },
};
